version: '3'
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile.Server
    volumes:
      - servervol:/serverdata
    expose:
      - "12345" # Expose the port the server is listening on
    networks:
      - mynetwork
volumes:
  servervol:

networks:
  mynetwork:
    external: true
